"""password_secure added

Revision ID: 8b85db8f86a7
Revises: b534159cfbdd
Create Date: 2020-09-17 16:27:04.802265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b85db8f86a7'
down_revision = 'b534159cfbdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_hash')
    # ### end Alembic commands ###
